version: '2.2'
services:
  tidal-connect:
    image: edgecrush3r/tidal-connect:latest
    tty: true
    network_mode: host
    devices:
     - /dev/snd
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - /var/run/dbus:/var/run/dbus
      #- /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

